
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
#################################################
# file to edit: notebook.ipynb͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

import time
from isolation import Board

# Credits if any͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
# 1)͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
# 2)͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
# 3)͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

class OpenMoveEvalFn:
    def score(self, game, my_player=None):
        """Score the current game state
        Evaluation function that outputs a score equal to how many
        moves are open for AI player on the board minus how many moves
        are open for Opponent's player on the board.

        Note:
            If you think of better evaluation function, do it in CustomEvalFn below.

            Args
                game (Board): The board and game state.
                my_player (Player object): This specifies which player you are.

            Returns:
                float: The current state's score. MyMoves-OppMoves.

            """

        # TODO: finish this function!͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
        my_move=game.get_player_moves(my_player)
        opponent_move=game.get_opponent_moves(my_player)
        score=len(my_move)-len(opponent_move)
        return score
        # raise NotImplementedError



######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

class CustomEvalFn:
    def __init__(self):
        pass

    def score(self, game, my_player=None):
        """Score the current game state.

        Custom evaluation function that acts however you think it should. This
        is not required but highly encouraged if you want to build the best
        AI possible.

        Args:
            game (Board): The board and game state.
            my_player (Player object): This specifies which player you are.

        Returns:
            float: The current state's score, based on your own heuristic.
        """
        #Get total number of moves of Opponent
        my_move=game.get_player_moves(my_player)
        opponent_move=game.get_opponent_moves(my_player)
        if len(my_move)==0:
            return float('-inf')
        if len(opponent_move)==0:
            return float('inf')

        killer_move=0
        for move in my_move:
            forecast_game, _, _ = game.forecast_move(move)
            new_opponent_move=forecast_game.get_opponent_moves(my_player)
            if len(new_opponent_move)<=2:
                killer_move+=1
        score=len(my_move)-len(opponent_move) + killer_move*0.5
        return score
        # # TODO: finish this function!͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
        # if my_player:
        # my_move=game.get_player_moves(my_player)
        # opponent_move=game.get_opponent_moves(my_player)
        # if len(my_move)==0:
        #     return float('-inf')
        # elif len(opponent_move)==0:
        #     return float('inf')
        # else:
        #     # killer_move=0
        #     # for move in my_move:
        #     #     forecast_game, _, _ = game.forecast_move(move)
        #     #     # new_opponent_move=forecast_game.get_opponent_moves(my_player)
        #     #     new_move=forecast_game.get_player_moves(my_player)
        #     #     # if len(new_opponent_move)<=1:
        #     #     #     killer_move+=1
        #     #     if len(new_move)<=1:
        #     #         continue
        #     return len(my_move)-len(opponent_move)
            # score=len(my_move)-len(opponent_move) + killer_move*0.5
            # return score
        # else:
        #     my_move=game.get_player_moves(game._active_player_)
        #     opponent_move=game.get_opponent_moves(game._active_player_)
        #     return len(my_move)-len(opponent_move)


######################################################################
############ DON'T WRITE ANY CODE OUTSIDE THE CLASS! #################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######################################################################

class CustomPlayer:
    # TODO: finish this class!͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    """Player that chooses a move using your evaluation function
    and a minimax algorithm with alpha-beta pruning.
    You must finish and test this player to make sure it properly
    uses minimax and alpha-beta to return a good move."""

    def __init__(self, search_depth=3, eval_fn=OpenMoveEvalFn()):
        """Initializes your player.
        #CustomEvalFn
        #OpenMoveEvalFn
        if you find yourself with a superior eval function, update the default
        value of `eval_fn` to `CustomEvalFn()`

        Args:
            search_depth (int): The depth to which your agent will search
            eval_fn (function): Evaluation function used by your agent
        """
        self.eval_fn = eval_fn
        self.search_depth = search_depth

    def move(self, game, time_left):
        """Called to determine one move by your agent

        Note:
            1. Do NOT change the name of this 'move' function. We are going to call
            this function directly.
            2. Call alphabeta instead of minimax once implemented.
        Args:
            game (Board): The board and game state.
            time_left (function): Used to determine time left before timeout

        Returns:
            tuple: (int,int): Your best move
        """
        # best_move, utility = minimax(self, game, time_left, depth=self.search_depth)
        # # best_move, utility = alphabeta(self,game, time_left, depth=self.search_depth, alpha=float("-inf"), beta=float("inf"))
        # return best_move
        best_move=None
        current_depth=self.search_depth
        best_val=float('-inf')
        if game.move_count==0:
            best_move=((game.height)//2,(game.width)//2)
            if game.is_spot_open(best_move[0],best_move[1]):
                return best_move
        # start_time=time.time()
        # try:
        #     while True:
        #         if time_left()+start_time<50+start_time:
        #             break
        #         best_move, utility = alphabeta(self,game, time_left, depth=self.search_depth, alpha=float("-inf"), beta=float("inf"))
        #         # best_move, utility = minimax(self, game, time_left, depth=self.search_depth)
        #         # current_depth+=1
        #         return best_move
        # except TimeoutError:
        #     return best_move
        for i in range(current_depth):
            if time_left()<50: break
            best_move, utility = alphabeta(self,game, time_left, i, alpha=float("-inf"), beta=float("inf"))
            # if utility>best_val:
            #     best_move=alpha_move
        return best_move
    def utility(self, game, my_turn):
        """You can handle special cases here (e.g. endgame)"""
        return self.eval_fn.score(game, self)

###################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE CLASS! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
###### IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ###########͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
###################################################################


def minimax(player, game, time_left, depth, my_turn=True):
    """Implementation of the minimax algorithm.
    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you
            need from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer()).
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """

    # TODO: finish this function!͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError
    legal_moves = game.get_active_moves()
    if depth == 0 or not legal_moves:
        return None, player.utility(game, player)

    best_move = None
    if my_turn:
        max_val = float('-inf')
        for move in legal_moves:
            forecast_game, is_over, _ = game.forecast_move(move)
            if is_over:
                return move, player.utility(game, forecast_game)
            _, score = minimax(player,forecast_game, time_left, depth - 1, False)
            if score > max_val:
                max_val = score
                best_move = move
        return best_move, max_val
    else:
        min_val = float('inf')
        for move in legal_moves:
            forecast_game, _, _ = game.forecast_move(move)
            _, score = minimax(player,forecast_game, time_left, depth - 1, True)
            if score < min_val:
                min_val = score
                best_move = move
        return best_move, min_val
######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
# tests.minimaxTest(CustomPlayer, minimax)
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

def alphabeta(player, game, time_left, depth, alpha=float("-inf"), beta=float("inf"), my_turn=True):
    """Implementation of the alphabeta algorithm.

    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you need
            from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer())
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        alpha (float): Alpha value for pruning
        beta (float): Beta value for pruning
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """
    legal_moves=game.get_active_moves()
    killer_move=[None,None]
    if depth==0 or not legal_moves:
        return None, player.utility(game, player)
    best_move=None
    score=0
    if my_turn:
        for move in legal_moves:
            if move in killer_move:
                forecast_game, is_over, _ = game.forecast_move(move)
                if is_over:
                    return move, player.utility(game, forecast_game)
                    # break
                # if len(forecast_game.get_active_moves())<=1:
                #     continue
                # else:
                _, score = alphabeta(player,forecast_game, time_left, depth - 1, alpha, beta, False)
                if score > alpha:
                    alpha = score
                    best_move = move
                if alpha>=beta:
                    break
            else:
                forecast_game, is_over, _ = game.forecast_move(move)
                if is_over:
                    return move, player.utility(game, forecast_game)
                    # break
                # if len(forecast_game.get_active_moves())<=1:
                #     continue
                # else:
                _, score = alphabeta(player,forecast_game, time_left, depth - 1, alpha, beta, False)
                if score > alpha:
                    alpha = score
                    best_move = move
                if alpha>=beta:
                    if killer_move[1]==None:
                        killer_move[1]=move
                    elif killer_move[0]==None:
                        killer_move[0]=move
                    else:
                        killer_move[0]=killer_move[1]
                        killer_move[1]=move
                    break
        return best_move, alpha
    else:
        for move in legal_moves:
            if move in killer_move:
                forecast_game, is_over, _ = game.forecast_move(move)
                if is_over:
                    # break
                    return move, player.utility(game, forecast_game)
                # if len(forecast_game.get_active_moves())<=1:
                #     break
                # else:
                _, score = alphabeta(player,forecast_game, time_left, depth - 1, alpha, beta, True)
                if score < beta:
                    beta = score
                    best_move = move
                if alpha>=beta:
                    break
            else:
                forecast_game, is_over, _ = game.forecast_move(move)
                if is_over:
                    return move, player.utility(game, forecast_game)
                    # break
                # if len(forecast_game.get_active_moves())<=1:
                #     score=float('-inf')
                # else:
                _, score = alphabeta(player,forecast_game, time_left, depth - 1, alpha, beta, True)
                if score < beta:
                    beta = score
                    best_move = move
                if alpha>=beta:
                    if killer_move[1]==None:
                        killer_move[1]=move
                    elif killer_move[0]==None:
                        killer_move[0]=move
                    else:
                        killer_move[0]=killer_move[1]
                        killer_move[1]=move
        return best_move, beta
    # # TODO: finish this function!͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError


######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
# tests.name_of_the_test #you can uncomment this line to run your test͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
# tests.minimaxTest(CustomPlayer, alphabeta)
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

# class CustomEvalFn:
#     def __init__(self):
#         pass

#     def score(self, game, my_player=None):
#         """Score the current game state.

#         Custom evaluation function that acts however you think it should. This
#         is not required but highly encouraged if you want to build the best
#         AI possible.

#         Args:
#             game (Board): The board and game state.
#             my_player (Player object): This specifies which player you are.

#         Returns:
#             float: The current state's score, based on your own heuristic.
#         """

#         # TODO: finish this function!͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
#         raise NotImplementedError

######################################################################
############ DON'T WRITE ANY CODE OUTSIDE THE CLASS! #################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
######################################################################