
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
#################################################
# file to edit: notebook.ipynb͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

import numpy as np
import operator

def part_1_a():
    """Provide probabilities for the word HMMs outlined below.
    Word ALLIGATOR, NUTS, and SLEEP.
    Review Udacity Lesson 8 - Video #29. HMM Training
    Returns:
        tuple() of
        (prior probabilities for all states for word ALLIGATOR,
         transition probabilities between states for word ALLIGATOR,
         emission parameters tuple(mean, std) for all states for word ALLIGATOR,
         prior probabilities for all states for word NUTS,
         transition probabilities between states for word NUTS,
         emission parameters tuple(mean, std) for all states for word NUTS,
         prior probabilities for all states for word SLEEP,
         transition probabilities between states for word SLEEP,
         emission parameters tuple(mean, std) for all states for word SLEEP)
        Sample Format (not complete):
        (
            {'A1': prob_of_starting_in_A1, 'A2': prob_of_starting_in_A2, ...},
            {'A1': {'A1': prob_of_transition_from_A1_to_A1,
                    'A2': prob_of_transition_from_A1_to_A2,
                    'A3': prob_of_transition_from_A1_to_A3,
                    'Aend': prob_of_transition_from_A1_to_Aend},
             'A2': {...}, ...},
            {'A1': tuple(mean_of_A1, standard_deviation_of_A1),
             'A2': tuple(mean_of_A2, standard_deviation_of_A2), ...},
            {'N1': prob_of_starting_in_N1, 'N2': prob_of_starting_in_N2, ...},
            {'N1': {'N1': prob_of_transition_from_N1_to_N1,
                    'N2': prob_of_transition_from_N1_to_N2,
                    'N3': prob_of_transition_from_N1_to_N3,
                    'Nend': prob_of_transition_from_N1_to_Nend},
             'N2': {...}, ...}
            {'N1': tuple(mean_of_N1, standard_deviation_of_N1),
             'N2': tuple(mean_of_N2, standard_deviation_of_N2), ...},
            {'S1': prob_of_starting_in_S1, 'S2': prob_of_starting_in_S2, ...},
            {'S1': {'S1': prob_of_transition_from_S1_to_S1,
                    'S2': prob_of_transition_from_S1_to_S2,
                    'S3': prob_of_transition_from_S1_to_S3,
                    'Send': prob_of_transition_from_S1_to_Send},
             'S2': {...}, ...}
            {'S1': tuple(mean_of_S1, standard_deviation_of_S1),
             'S2': tuple(mean_of_S2, standard_deviation_of_S2), ...}
        )
    """

    # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError()

    """Word ALLIGATOR"""
    a_prior_probs = {
        'A1': 0.333,
        'A2': 0.000,
        'A3': 0.000,
        'Aend': 0.000
    }
    a_transition_probs = {
        'A1': {'A1': 0.833, 'A3': 0.000, 'A2': 0.167, 'Aend': 0.000},
        'A2': {'A1': 0.000, 'A2': 0.786, 'A3': 0.214, 'Aend': 0.000},
        'A3': {'A2': 0.000, 'A3': 0.727, 'A1': 0.000, 'Aend': 0.273},
        'Aend': {'A1': 0.000, 'A3': 0.000, 'A2': 0.000, 'Aend': 1.000}
    }
    # Parameters for end state is not required͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    a_emission_paras = {
        'A1': (51.056, 21.986),
        'A2': (28.357, 14.936),
        'A3': (53.727, 16.707),
        'Aend': (None, None)
    }

    """Word NUTS"""
    n_prior_probs = {
        'N1': 0.333,
        'N2': 0.000,
        'N3': 0.000,
        'Nend': 0.000
    }
    # Probability of a state changing to another state.͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    n_transition_probs = {
        'N1': {'N3': 0.000, 'N1': 0.919, 'N2': 0.081, 'Nend': 0.000},
        'N2': {'N3': 1.000, 'N1': 0.000, 'N2': 0.000, 'Nend': 0.000},
        'N3': {'N3': 0.625, 'N1': 0.000, 'N2': 0.000, 'Nend': 0.375},
        'Nend': {'N3': 0.000, 'N2': 0.000, 'N1': 0.000, 'Nend': 1.000}
    }
    # Parameters for end state is not required͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    n_emission_paras = {
        'N1': (38.081, 11.175),
        'N2': (42.000, 2.828),
        'N3': (60.000, 13.491),
        'Nend': (None, None)
    }

    """Word SLEEP"""
    s_prior_probs = {
        'S1': 0.333,
        'S2': 0.000,
        'S3': 0.000,
        'Send': 0.000
    }
    s_transition_probs = {
        'S1': {'S1': 0.625, 'S2': 0.375, 'S3': 0.000, 'Send': 0.000},
        'S2': {'S3': 0.136, 'S2': 0.864, 'S1': 0.000, 'Send': 0.000},
        'S3': {'S1': 0.000, 'S2': 0.000, 'S3': 0.000, 'Send': 1.000},
        'Send': {'S1': 0.000, 'S2': 0.000, 'S3': 0.000, 'Send': 1.000}
    }
    # Parameters for end state is not required͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    s_emission_paras = {
        'S1': (29.500, 8.411),
        'S2': (36.182, 5.990),
        'S3': (36.667, 1.886),
        'Send': (None, None)
    }

    return (a_prior_probs, a_transition_probs, a_emission_paras,
            n_prior_probs, n_transition_probs, n_emission_paras,
            s_prior_probs, s_transition_probs, s_emission_paras)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

def gaussian_prob(x, para_tuple):
    """Compute the probability of a given x value

    Args:
        x (float): observation value
        para_tuple (tuple): contains two elements, (mean, standard deviation)

    Return:
        Probability of seeing a value "x" in a Gaussian distribution.

    Note:
        We simplify the problem so you don't have to take care of integrals.
        Theoretically speaking, the returned value is not a probability of x,
        since the probability of any single value x from a continuous
        distribution should be zero, instead of the number outputted here.
        By definition, the Gaussian percentile of a given value "x"
        is computed based on the "area" under the curve, from left-most to x.
        The probability of getting value "x" is zero because a single value "x"
        has zero width, however, the probability of a range of value can be
        computed, for say, from "x - 0.1" to "x + 0.1".

    """
    if list(para_tuple) == [None, None]:
        return 0.0

    mean, std = para_tuple
    gaussian_percentile = (2 * np.pi * std**2)**-0.5 * \
                          np.exp(-(x - mean)**2 / (2 * std**2))
    return gaussian_percentile



def initial_state(O, O_prev, path, states, prior_probs, emission_paras, evidence_vector, multi_d=False):
    for s in states:
        if not multi_d:
            O[0][states.index(s)] = prior_probs[s] * gaussian_prob(evidence_vector[0], emission_paras[s])
        else:
            O[0][states.index(s)] = prior_probs[s] * gaussian_prob(evidence_vector[0][0], emission_paras[s][0]) * gaussian_prob(evidence_vector[0][1], emission_paras[s][1])
        O_prev[0][states.index(s)] = -1
        path[states.index(s)][0] = states.index(s)

def calculate_max_probability(O, O_prev, path, t, states, transition_probs, emission_paras, evidence_vector, multi_d=False):
    new_path = np.zeros_like(path)
    for s in states:
        prob = -1
        state = -1
        for s1 in states:
            if s in transition_probs[s1]:
                if not multi_d:
                    prbs_0 = (
                        O[t - 1][states.index(s1)]
                        * transition_probs[s1][s]
                        * gaussian_prob(evidence_vector[t], emission_paras[s])
                    )
                else:
                    prbs_0 = (
                        O[t - 1][states.index(s1)]
                        * transition_probs[s1][s][0]
                        * transition_probs[s1][s][1]
                        * gaussian_prob(evidence_vector[t][0], emission_paras[s][0])
                        * gaussian_prob(evidence_vector[t][1], emission_paras[s][1])
                    )
                if prbs_0 > prob:
                    prob = prbs_0
                    state = states.index(s)
                    O[t][states.index(s)] = prob
                    O_prev[t][states.index(s)] = states.index(s1)
                    new_path[states.index(s)][:t] = path[state][:t]
                    new_path[states.index(s)][t] = states.index(s)
    return new_path

def backtrack_path(O_prev, states, evidence_vector, state):
    path = []
    store = state
    path.append(states[store])

    for t in range(len(evidence_vector) - 1, 0, -1):
        store = O_prev[t][store]
        path.append(states[store])

    path.reverse()
    return path



def viterbi(evidence_vector, states, prior_probs,
            transition_probs, emission_paras):
    """Viterbi Algorithm to calculate the most likely states give the evidence.
    Args:
        evidence_vector (list): List of right hand Y-axis positions (integer).
        states (list): List of all states in a word. No transition between words.
                       example: ['A1', 'A2', 'A3', 'Aend', 'N1', 'N2', 'N3', 'Nend']
        prior_probs (dict): prior distribution for each state.
                            example: {'X1': 0.25,
                                      'X2': 0.25,
                                      'X3': 0.25,
                                      'Xend': 0.25}
        transition_probs (dict): dictionary representing transitions from each
                                 state to every other valid state such as for the above
                                 states, there won't be a transition from 'A1' to 'N1'
        emission_paras (dict): parameters of Gaussian distribution
                                from each state.
    Return:
        tuple of
        ( A list of states the most likely explains the evidence,
          probability this state sequence fits the evidence as a float )
    Note:
        You are required to use the function gaussian_prob to compute the
        emission probabilities.
    """

    # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError()

    sequence = []
    probability = 0.0

    # return sequence, probability
    T = len(evidence_vector)
    S = len(states)
    if T > 0:
        O = [[0.0] * S for _ in range(T)]
        O_prev = [[-1] * S for _ in range(T)]
        path = [[0] * T for _ in range(S)]

        initial_state(O, O_prev, path, states, prior_probs, emission_paras, evidence_vector)

        for i in range(1, len(evidence_vector)):
            path = calculate_max_probability(O, O_prev, path, i, states, transition_probs, emission_paras, evidence_vector)
        state = -1
        for s in states:
            if O[T - 1][states.index(s)] > probability:
                probability = O[T - 1][states.index(s)]
                state = states.index(s)
        sequence = backtrack_path(O_prev, states, evidence_vector, state)
        return sequence, probability
    else:
        return None, 0

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

def part_2_a():
    """Provide probabilities for the word HMMs outlined below.
    Now, at each time frame you are given 2 observations (right hand Y
    position & right thumb Y position). Use the result you derived in
    part_1_a, accompany with the provided probability for right thumb, create
    a tuple of (right-hand-y, right-thumb-y) to represent high-dimension transition &
    emission probabilities.
    """

     # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError()

    """Word ALLIGATOR"""
    a_prior_probs = {
        'A1': 0.333,
        'A2': 0.,
        'A3': 0.,
        'Aend': 0.
    }
    # example: {'A1': {'A1' : (right-hand Y, right-thumb Y), ... }͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    a_transition_probs = {
        'A1': {'A1': (0.833, 0.824), 'A3': (0., 0.), 'A2': (0.167, 0.176), 'Aend': (0., 0.)},
        'A2': {'A3': (0.214, 0.231), 'A2': (0.786, 0.769), 'A1': (0., 0.), 'Aend': (0., 0.)},
        'A3': {'A1': (0., 0.), 'A3': (0.727, 0.769), 'A2': (0., 0.), 'Aend': (0.273, 0.231)},
        'Aend': {'A3': (0., 0.), 'A2': (0., 0.), 'A1': (0., 0.), 'Aend': (1.000, 1.000)}
    }
    # example: {'A1': [(right-hand-mean, right-thumb-std), (right-hand--mean, right-thumb-std)] ...}͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    a_emission_paras = {
        'A1': [(51.056, 21.986), (53.529, 17.493)],
        'A2': [(28.357, 14.936), (40.769, 6.104)],
        'A3': [(53.727, 16.707), (51.000, 12.316)],
        'Aend': [(None, None), (None, None)]
    }

    """Word NUTS"""
    n_prior_probs = {
        'N1': 0.333,
        'N2': 0.,
        'N3': 0.,
        'Nend': 0.
    }
    n_transition_probs = {
        'N1': {'N2': (0.081, 0.136), 'N3': (0., 0.), 'N1': (0.919, 0.864), 'Nend': (0., 0.)},
        'N2': {'N2': (0., 0.727), 'N1': (0., 0.), 'N3': (1.000, 0.273), 'Nend': (0., 0.)},
        'N3': {'N1': (0., 0.), 'N2': (0., 0.), 'N3': (0.625, 0.800), 'Nend': (0.375, 0.200)},
        'Nend': {'N1': (0., 0.), 'N3': (0., 0.), 'N2': (0., 0.), 'Nend': (1.000, 1.000)}
    }
    n_emission_paras = {
        'N1': [(38.081, 11.175), (36.318, 7.376)],
        'N2': [(42.000, 2.828), (60.000, 15.829)],
        'N3': [(60.000, 13.491), (37.476, 8.245)],
        'Nend': [(None, None), (None, None)]
    }

    """Word SLEEP"""
    s_prior_probs = {
        'S1': 0.333,
        'S2': 0.,
        'S3': 0.,
        'Send': 0.
    }
    s_transition_probs = {
        'S1': {'S1': (0.625, 0.786), 'S2': (0.375, 0.214), 'S3': (0., 0.), 'Send': (0., 0.)},
        'S2': {'S1': (0., 0.), 'S2': (0.864, 0.769), 'S3': (0.136, 0.231), 'Send': (0., 0.)},
        'S3': {'S1': (0., 0.), 'S3': (0., 0.500), 'S2': (0., 0.), 'Send': (1.000, 0.500)},
        'Send': {'S1': (0., 0.), 'S2': (0., 0.), 'S3': (0., 0.), 'Send': (1.000, 1.000)}
    }
    s_emission_paras = {
        'S1': [(29.500, 8.411), (35.357, 7.315)],
        'S2': [(36.182, 5.990), (31.462, 5.048)],
        'S3': [(36.667, 1.886), (38.333, 7.409)],
        'Send': [(None, None), (None, None)]
    }

    return (a_prior_probs, a_transition_probs, a_emission_paras,
            n_prior_probs, n_transition_probs, n_emission_paras,
            s_prior_probs, s_transition_probs, s_emission_paras)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

def multidimensional_viterbi(evidence_vector, states, prior_probs,
                             transition_probs, emission_paras):
    """Decode the most likely word phrases generated by the evidence vector.
    States, prior_probs, transition_probs, and emission_probs will now contain
    all the words from part_2_a.
    Evidence vector is a list of tuples where the first element of each tuple is the right
    hand coordinate and the second element is the right thumb coordinate.
    """
    # TODO: complete this function.͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError()

    sequence = []
    probability = 0.0
    T = len(evidence_vector)
    S = len(states)
    if T > 0:
        O = [[0.0] * S for _ in range(T)]
        O_prev = [[-1] * S for _ in range(T)]
        path = [[0] * T for _ in range(S)]

        initial_state(O, O_prev, path, states, prior_probs, emission_paras, evidence_vector, True)

        for i in range(1, len(evidence_vector)):
            path = calculate_max_probability(O, O_prev, path, i, states, transition_probs, emission_paras, evidence_vector, True)
        state = -1
        for s in states:
            if O[T - 1][states.index(s)] > probability:
                probability = O[T - 1][states.index(s)]
                state = states.index(s)
        sequence = backtrack_path(O_prev, states, evidence_vector, state)
        return sequence, probability
    else:
        return None, 0

    # return sequence, probability

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
################ END OF LOCAL TEST CODE SECTION ######################͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀

def return_your_name():
    """Return your name
    """
    # TODO: finish this͏︆͏󠄃͏󠄌͏󠄍͏︅͏︀͏︋͏︋͏󠄄͏︁͏︀
    # raise NotImplementedError()

    return 'Ruixiang Huang'